name: CI Day 4 - Production style

on:
    pull_request:
        branches:
            - main

jobs:
    build_and_test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Show system info
              run: |
                echo " Running on:"
                uname -a
                df -h
            - name: Make script executable
              run: chmod +x ./scripts/check_disk.sh

            - name: Run disk check script
              run: ./scripts/check_disk.sh
    deploy:
        needs: build_and_test
        runs-on: ubuntu-latest
        if: github.event_name == 'push' && github.ref == 'refs/head/main'

        steps:
            -  name: Deploy app
               run: echo "Deployed to production"