name: CI basics

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Show system info
              run: |
                echo " Running on:"
                uname -a
                df -h

            - name: Run disk check script
              run: ./scripts/check_disk.sh

            - name: Run only if all disks are passed
              run: echo "Disk check passed, continuing pipeline"